apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespae: roboshop
spec:
  selecotr:
  matchLabels:
    project: roboshop
    component: rabbitmq
    tier: backend
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
