apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: loadbalancer
  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
